### ISSUE TITLE
Can't build for iOS simulator on arm64 Mac computer

### ISSUE THREAD

**Issue by MichaelSL** [beto-rodriguez/LiveCharts2#1063]
**Describe the bug**
When I try to build my application which uses LiveCharts2 for iOS Simulator on arm64 Mac I get the following error:

```
clang++ exited with code 1:
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/michael/Library/Caches/Xamarin/mtbs/builds/Tripsta/aeec817e023fc4d3a63619795aaa688cc328fc8828ed80ecf5ca133f3233a78d/C:/Users/Michael/.nuget/packages/skiasharp.nativeassets.ios/2.88.3/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)	Tripsta	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7060\targets\Xamarin.Shared.Sdk.targets	1274	
```

**To Reproduce**
1. Create a .NET MAUI Application
2. Reference `LiveChartsCore.SkiaSharpView.Maui`
3. Try to run your application on Simulator using Apple Silicon ARM64 Mac machine as a build host

**Expected behavior**
The application is built successfully and started on Simulator

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 with Visual Studio + MacOSX Ventura 13.4 as a build host

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: iOS16.4

**Additional context**
Build still works for:
- physical device
- for Simulator if using Intel based Mac as a build host

**Comment by beto-rodriguez** [comment]
Thanks for the report, it seems that the SkiaSharp team already got this, this should be fixed with https://github.com/mono/SkiaSharp/pull/2468 in a future version of LiveCharts we will reference a version that contains that fix.

I will keep this open as reminder to update that.

**Comment by mattleibow** [comment]
If you download the nuget artifacts from that PR, does LiveCharts start working?
https://dev.azure.com/xamarin/public/_build/results?buildId=88754&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by mattleibow** [comment]
I merged the change, there should be an update appearing in a few hours on the preview feed: https://aka.ms/skiasharp-eap/index.json

**Comment by beto-rodriguez** [comment]
thanks for the update! @mattleibow

**Comment by maslewandowski** [comment]
Does skiasharp generally work on ios devices? I tried to get it working with the [startup documentation](https://lvcharts.com/docs/Maui/2.0.0-beta.800/Overview.Installation) but unfortunately, it works on android emulator but not on ipad pro deployed via usb / hot restart.

**Comment by beto-rodriguez** [comment]
@maslewandowski SkiaSharp works on IOS, the problem seems to be in this library, probably related to #800, I am trying to fix that for the next release.

**Comment by MichaelSL** [comment]
Updated `LiveChartsCore.SkiaSharpView.Maui` from `2.0.0-beta.701` to `2.0.0-beta.810` - issue is still reproducable.
Real devise (iPhone) deploy still works

**Comment by beto-rodriguez** [comment]
@MichaelSL version beta.850 uses the latest version of SkiaSharp, it should be fixed on that version, is it working for you?

**Comment by MichaelSL** [comment]
@beto-rodriguez  I can confirm `beta.850` fixed the issue with simulator, app build ok and launches on simulator.

It broke my custom gauge though ;)

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/2205113/1801072f-aca6-4a1c-b29f-27574997087a)

**Comment by beto-rodriguez** [comment]
we can track that in another issue, thanks for the feedback! feel free to open a new issue with the case!

**Comment by MichaelSL** [comment]
@beto-rodriguez  yep, sure; this one is fixed and should be closed. I think my issue is because I was scaling the graph according to screen density and you've added the inbuilt scaling support in 850.1. Most likely I'll just have to remove my scaling and it should work. Not sure it needs an issue, maybe just mention that somewhere so folks who scaled manually would know.

**Comment by beto-rodriguez** [comment]
yes, Livecharts for Maui now looks better on different devices
