### ISSUE TITLE
The LiveChart for Uno Wasm is rendering on locally in webbrowser. But when hosting in IIS it is rendering in localhost:50 (where 50 is port number) for eg http://localhost:50/. But not rendering on when trying using ipaddres with port number for eg: http://192.168.1.103:50/

### ISSUE THREAD

**Issue by tomchoondal** [beto-rodriguez/LiveCharts2#1569]
**Describe the bug**
The LiveChart for Uno Wasm is rendering on locally in web browser. When hosting in IIS it is rendering in localhost:50 (where 50 is port number) for eg http://localhost:50/. But not rendering on when trying using IP address with port number for eg: http://192.168.1.103:50/

**To Reproduce**
I am attaching the sample code.

**Expected behavior**
The chart should be accessble via ip address as well so that the app can be hosted in a VM and app can be accessed using ip address when computers in same network.

**Screenshots**
Screenshot 1: The chart is rendering on localhost:50
![image](https://github.com/user-attachments/assets/803a6e9d-2f3b-4335-a487-e9420a156957)

Screenshot 2: The chart is not rendering on http://192.168.1.103:50/
![image](https://github.com/user-attachments/assets/f6680439-013d-469a-a119-e8b86ca4dda8)

Browser: Edge
Uno version 5.3.18.22

**Additional context**
I am an employee of Baker Hughes, and we are working a data visualization app using uno platform. we need to host this application in VM's cannot host in a server or cloud because the rig machines will not have an active internet. We will host this app in a VM using IIS. And any users connected to baker network can access the app using hosted machine's IP Address. This is the configuration flow of the app. We can only proceed further if we get a clarity on above mentioned issue.
[UnoSampleCharApp[1].zip](https://github.com/user-attachments/files/16639423/UnoSampleCharApp.1.zip)

**Comment by Youssef1313** [comment]
@tomchoondal If you open the browser's console, do you see any errors/warnings?

**Comment by tomchoondal** [comment]
> @tomchoondal If you open the browser's console, do you see any errors/warnings?
Yes!
![image](https://github.com/user-attachments/assets/04772b9b-5df5-4256-93f1-645d9894a7fa)

**Comment by tomchoondal** [comment]
I will share the errors I am getting in both cases
Case1: using localhost
![image](https://github.com/user-attachments/assets/14791f5e-6de8-469c-8cb6-11dbc7afbce7)

Case 2: using ipaddress of machine 
![image](https://github.com/user-attachments/assets/d045405e-1d2c-48be-9272-1919d41297e8)

**Comment by ebariche** [comment]
@tomchoondal, There is a bug in SKXamlCanvas when then browser is not in a secure context. We'll work with MS to resolve it. Switch to HTTPS for now.

**Comment by tomchoondal** [comment]
@Youssef1313  and @ebariche  Thank you for your valuable comments. The issue is solved when hosted in https format.

**Comment by MateralCMX** [comment]
I'm encountering this issue. 
error: IndexSizeError: Failed to construct 'ImageData': The input data length is not a multiple of (4 * width).

<img width="1455" height="60" alt="Image" src="https://github.com/user-attachments/assets/77cfecc7-c816-4d28-b8e6-7bf72604c65f" />

The reproduction demo can be found here:：
https://github.com/MateralCMX/LiveChatsUnoDemo

Where：
[LiveChatsDemo](https://github.com/MateralCMX/LiveChatsUnoDemo/tree/master/LiveChatsDemo)uses SkiaRenderer not exhibit this issue
[LiveChatsDemo2](https://github.com/MateralCMX/LiveChatsUnoDemo/tree/master/LiveChatsDemo2)does not use SkiaRenderer this issue.

Specific reproduction steps are demonstrated in the video:
[LiveChatsDemo.mp4](https://github.com/MateralCMX/LiveChatsUnoDemo/blob/master/LiveChatsDemo.mp4)
Due to network restrictions, I was unable to upload the video directly.

However, SkiaRenderer cannot be used due to issue:
https://github.com/unoplatform/uno/issues/20292

**Comment by MateralCMX** [comment]
I found this issue is related to HTTPS, as the error disappeared when I accessed it via HTTPS.
[I hosted the generated program using nginx, configured with both HTTPS (SSL certificate) and HTTP. The issue persists under HTTP but disappears under HTTPS.]

**Comment by beto-rodriguez** [comment]
Now `rc-6` version is integreated with the Uno SkiaRender, you should give it a try, maybe a lof of these issues are gone in the latest version.
