### ISSUE TITLE
Legend values sometimes dont display

### ISSUE THREAD

**Issue by rpascalegh** [beto-rodriguez/LiveCharts2#861]
**Describe the bug**
Pie chart legend shows values correctly.  Run the app again and they sometimes dont show.  The Seperator shows, but values dont.   When I load new data into pie, the legend data is not updating when Seriers is updated.  All the values change correctly, and the pie values update correctly, but the legend data does not update.   I am testing and seeing values in legend not updating.  

Using Same code on different versions Live Chart Versions.
In version .400 same code worked  when "VALUES" is updated pie values update, when "NAME" is updated legend values update.
In version .603 same code when "VALUES" is updated pie values update, when "NAME" is updated legend DO NOT update.

**To Reproduce**
Load Values into pie.  Run app over to cause issue.
loading pie data
  for (int i = 0; i < report.xvalues.Count; i++)
                            {
                                Chart4.Series[i].Values = new List<double> { report.posted[i] };
                                Chart4.Series[i].Name = report.xvalues[i] + "\n" + Math.Round(report.posted[i] / 1000000, 3).ToString();
                            }

**Expected behavior**
Legend values to show

**Screenshots**
![pie](https://user-images.githubusercontent.com/14371980/210077181-78c0c996-b85e-47cb-b1f4-d7cdb7b29b29.png)

**Desktop (please complete the following information):**
Win 10 , VS 2022 Dot net Maui

**Smartphone (please complete the following information):**
Android Samsung S21+

**Additional context**
Using .603 because .700 crashes.

**Comment by nabrezzelt** [comment]
Hey, I have the same problem, that the names in the legend aren't displayed. 

If the PieChart is displayed the first time, the names are visible. After the ObservableCollection changed, the names are missing/not visible.

I'm using version 2.0.0-beta.700

**Comment by rpascalegh** [comment]
I had to roll back to .400, waiting until this is corrected.

**Comment by jcalleBalder** [comment]
Hi, I have the same problem with the PieChart at WPF, it only shows at first time.
I'm using version 2.0.0-beta.700 too

**Comment by rpascalegh** [comment]
Has anyone found work around for this issue?

**Comment by network-interface-controller** [comment]
Unfortunately not, the problem still persists and seems to affect all chart types :(

@beto-rodriguez is there a chance to increase the priority of this issue? Vanishing legends after value changes are really annoying....

**Comment by rpascalegh** [comment]
Aww.  That means I can use .700 until a fix is done.   Having the lengend disappear is deal breaker.   You cant read a chart without knowing what it represents.

**Comment by beto-rodriguez** [comment]
This should be fixed soon

**Comment by rpascalegh** [comment]
Please note, I tested ver 710 , still has same issue with legend not alwasy appearing.

**Comment by AdrianVisnovsky** [comment]
Is there a approx release date for the new version?

**Comment by beto-rodriguez** [comment]
It is uploaded now/

**Comment by rpascalegh** [comment]
Ok.  Will test it. Thank you.
